### PR TITLE
Updates from deploying dap-blueprint in hpvs cloud

### PR DESCRIPTION
**Pull request by bfabec**
- Remove instructions for DCT and added instructions to use digest instead.  Redhat signing isn't ready to be used atm.
- Update rhsso redirect uri for kie server to include `approval-host`
- Updated the plain contracts to be correct yaml that is consumable within user data
- Various updates in the Deploy readme

### CODE REVIEW

**Comment by tnakaike** [comment]
@bfabec Thank you for your updates.

I have three comments.

- As far as I remember, us.icr.io still supports DCT (implicitly) though the document says that DCT is not supported. Did you have any error to use DTC in us.icr.io? If not, I would like to stay the optional document related to DCT (for our memo).
- It is a good idea to add the document for the use of digest instead of DCT. Where can I find the document to add a digest to DAP_IMAGE?
- Can you upgrade your hpcr provider instead of adding a contract encryption key? It looks like the latest hpcr provider includes the key you added (https://github.com/ibm-hyper-protect/terraform-provider-hpcr/tree/main/data).

**Comment by bfabec** [comment]
@tnakaike - 

1. As far as I can tell, it is no longer supported, even as optional. For example, the secure build command to get the dct public key `get-dct-publickey` no longer exits within the tooling.
2. The digest idea came from Carsten and he said that if the digest is used then neither DCT or RHS information on the image is required at all, and the digest is good enough, even the preferred approach from a CI/CD perspective since it guarantees reproducibility.  The Deploy instructions includes the digest step here https://github.com/IBM/dap-blueprint/blob/bfabec_hpvs_deploy/Deploy.md?plain=1#L414
3. Looks like Carsten updated the terraform plugin repo to include the new encryption key yesterday after our issue.   I will update the PR accordingly.

**Comment by bfabec** [comment]
@tnakaike - I have updated the PR with the updates. Thanks!

**Review by tnakaike — APPROVED** [review]
LGTM

**Pull request merged**
